stages:
  - check

check1:
  stage: check
  image: debian:latest
  before_script:
    - apt update
    - apt install -y fastd python3-minimal
  script:
    - for f in * ; do echo "checking $f..."; fastd --verify-config --config-peer "$f" || exit 1; done
    - ./.check.py
