language: c
sudo: required
dist: trusty
group: deprecated-2017Q4

before_install:
 - sudo apt-get install apt-transport-https
 - sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-keys 0x16EF3F64CB201D9C
 - echo "deb https://repo.universe-factory.net/debian/ sid main" | sudo tee -a /etc/apt/sources.list
 - sudo apt-get update
 - sudo apt-get install -y --force-yes fastd

script:
 - for f in * ; do echo "checking $f..."; fastd --verify-config --config-peer $f || exit 1; done
 - ./.check.py

notifications:
  irc:
    channels:
      - "irc.hackint.org#ffda"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
